### ISSUE TITLE
Generated Jar file doesn't contains extension classes

### ISSUE THREAD

**Issue by angel-aam** [wso2-extensions/siddhi-execution-reorder#46]
Hi, I am trying to use this extension in a bundled application as a library, imported by maven: 
```xml
        <dependency>
            <groupId>io.siddhi.extension.execution.reorder</groupId>
            <artifactId>siddhi-execution-reorder</artifactId>
            <version>5.0.2</version>
        </dependency>
```
which is lying at:
https://mvnrepository.com/artifact/io.siddhi.extension.execution.reorder/siddhi-execution-reorder/5.0.2

When the dependency is downloaded, looks like the jar contains just the `META-INF` folder, but the folders with the code are missing.

This might be caused due to the recent rename of the root package in versions 5.0.0 onwards, from `org.wso2.extension.siddhi.*` to `io.siddhi.extension.*`

but the `maven-bundle-plugin` configuration, still exports the old one.
https://github.com/siddhi-io/siddhi-execution-reorder/blob/ea318caff314e62c7692db02b352b3e4dc2004b5/component/pom.xml#L103

Many thanks! :)

**Comment by niveathika** [comment]
@angel-aam Thank you for reporting it. We will fix it and release the extension
